eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8091/eureka/ #配置注册中心地址
spring:
  application:
    name: shop-gateway
server:
  port: 9092
zuul:
  routes:
    shop-cate-api:
      path: /cate/**
    shop-goods-api:
      path: /goods/**
fh:
  shop:
    checkUrl: /api/member/findMember,/api/member/write,/api/cart/addCart,/api/cart/deleteCart,/api/cart/selectCart